RA-45 implement hilt dependency injection
druzhininSergey/RecipeApp pull request #37
Opened 2024-05-14 12:02 UTC by druzhininSergey

2024-05-17 18:05 UTC, danelyan requested changes

2024-05-17 18:05 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipes_list/RecipesListViewModel.kt
> +                recipesRepository.getRecipeListFromCache()
Тут проблема в том, что у тебя нет никакой связи в базе данных между рецептом и его категорией.
Давай:
- в Recipe добавим categoryId
- getRecipeListFromCache() сделаем метод  getRecipesByCategoryId(categoryId: Int)
- В дао добавим метод которые берет не все рецепты, а только соответствующий categoryId используя WHERE

2024-05-21 12:12 UTC, ievetrovdev approved these changes

2024-05-21 12:12 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/di/RecipeModule.kt
> +    fun provideRecipeIpiServise(retrofit: Retrofit): RecipeApiService =
опечатка RecipeApiService

2024-05-21 12:12 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/ItemDecoration.kt
> +import dagger.hilt.android.AndroidEntryPoint
Неиспользуемые импорты следует поубирать (с помощью автоформатирования)

2024-05-23 07:56 UTC, merged