Ra 07 basic category screen layout
druzhininSergey/RecipeApp pull request #5
Opened 2024-02-28 12:25 UTC by druzhininSergey

2024-03-01 10:00 UTC, ievetrov requested changes

2024-03-01 10:00 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +            android:text="@string/category" />
лучше конкретизировать, что это тайтл или текст. иначе при глобальном поиске потеряется

2024-03-01 10:00 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +        tools:ignore="UselessParent">
а этот атрибут тут нужен?

2024-03-01 10:00 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +            android:layout_height="224dp">
ресурсы

2024-03-01 10:00 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +        <androidx.recyclerview.widget.RecyclerView
Добавь еще атрибут tools:listitem="@layout/item_category"
Так ты увидишь на превьюхе в студии сверстанные карточки категории и как они будут выглядеть в приложении.

2024-03-01 10:00 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
Карточку надо сверстать. Представь, что элемент списка – это вот весь данный лейаут. Сделай для него верстку, заполни тестовыми данными в качестве картинки, названия и описания через атрибуты tools.

2024-03-01 10:00 UTC, ievetrov commented on app/src/main/res/mipmap-xxhdpi/categories_foreground.webp
убираем эту генерацию. изображение для категории просто копипастится в папку drawable. это сгенеренные иконки апки

2024-03-01 10:00 UTC, ievetrov commented on app/src/main/categories-playstore.png
это тоже не нужно

2024-03-02 04:20 UTC, druzhininSergey commented on app/src/main/res/layout/item_category.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
я ее сверстал в RA-08) но уже перенес в RA-07

2024-03-02 20:28 UTC, ievetrov requested changes
удаляем все сгенерированные файлы для изображения. мы его не будем использовать в качестве иконки приложения

<img width="638" alt="Снимок экрана 2024-03-03 в 00 27 34" src="https://github.com/druzhininSergey/RecipeApp/assets/34489023/b721ba51-0d6a-438c-9cf6-b91b940d520c">

2024-03-02 20:28 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +    android:clickable="true"
вот этот набор атрибутов можно вынести в стиль и переиспользовать

2024-03-02 20:28 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +    app:cardCornerRadius="8dp"
все значения не забывай выносить в ресурсы и переиспользовать оттуда

2024-03-02 20:28 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            tools:text="Вид блюда" />
нормально, можно прям замокать реальными названиями и описаниями любого блюда.

2024-03-04 11:54 UTC, druzhininSergey commented on app/src/main/res/layout/item_category.xml
> +            tools:text="Вид блюда" />
по контексту слово замокать означает заполнить? или как правильно понимать?))

2024-03-04 16:08 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            tools:text="Вид блюда" />
это означает типа заполнение фейковыми, ложными, тестовыми данными)

2024-03-04 16:09 UTC, ievetrov approved these changes

2024-03-05 02:57 UTC, merged